# Generated by Django 4.2.2 on 2023-07-26 13:47

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=455, null=True, upload_to=users.models.upload_to),
        ),
        migrations.AlterField(
            model_name='owner',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=455, null=True, upload_to=users.models.upload_to),
        ),
    ]
