# Generated by Django 4.2.2 on 2023-11-11 01:59

import appRumah.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FasilitasKamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Wc', 'Wc'), ('Lemari', 'Lemari'), ('Meja Belajar', 'Meja Belajar'), ('Kursi', 'Kursi'), ('Tempat Tidur', 'Tempat Tidur'), ('Kasur', 'Kasur'), ('Ac', 'Ac')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FasilitasRumah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Parkiran', 'Parkiran'), ('Kolam', 'Kolam'), ('Dapur Umum', 'Dapur Umum'), ('Wc Umum', 'Wc Umum'), ('Tangga', 'Tangga'), ('Lift', 'Lift'), ('CCTV', 'CCTV'), ('Lapangan', 'Lapangan'), ('Wifi', 'Wifi'), ('Tv Umum', 'Tv Umum'), ('Fasilitas Olahraga', 'Fasilitas Olahraga'), ('Security', 'Security'), ('Jasa Laundry', 'Jasa Laundry'), ('Kantin Umum', 'Kantin Umum'), ('Sarana Hiburan', 'Sarana Hiburan'), ('Cleaning Service', 'Cleaning Service')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_room', models.CharField(blank=True, max_length=150, null=True)),
                ('picture_room', models.ImageField(blank=True, max_length=455, null=True, upload_to=appRumah.models.upload_to)),
                ('room_size', models.CharField(blank=True, max_length=150, null=True)),
                ('price_day', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
                ('price_month', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
                ('price_year', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
                ('barang_dipesan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('type', models.CharField(choices=[('University', 'University'), ('Hospital', 'Hospital'), ('Stadium', 'Stadium')], max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('rate', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleKamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aturan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RuleRumah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aturan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rumah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('borough', models.CharField(blank=True, max_length=50, null=True)),
                ('no_rekening', models.CharField(blank=True, max_length=100, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('picture1', models.ImageField(blank=True, max_length=455, null=True, upload_to=appRumah.models.upload_to)),
                ('picture2', models.ImageField(blank=True, max_length=455, null=True, upload_to=appRumah.models.upload_to)),
                ('picture3', models.ImageField(blank=True, max_length=455, null=True, upload_to=appRumah.models.upload_to)),
                ('picture4', models.ImageField(blank=True, max_length=455, null=True, upload_to=appRumah.models.upload_to)),
                ('picture5', models.ImageField(blank=True, max_length=455, null=True, upload_to=appRumah.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buktiTransfer', models.ImageField(blank=True, max_length=455, null=True, upload_to=appRumah.models.upload_to)),
                ('nominal', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
                ('rentalFrequency', models.CharField(blank=True, choices=[('Year', 'Year'), ('Month', 'Month'), ('Day', 'Day')], max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('approve', models.BooleanField(default=False)),
            ],
        ),
    ]
