# Generated by Django 4.2.2 on 2023-11-12 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appRumah', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RuleKamar',
        ),
    ]
