# Generated by Django 4.2.2 on 2023-07-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='nominal',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True),
        ),
    ]
