# Generated by Django 4.2.2 on 2023-07-24 08:34

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_picture1_alter_listing_picture2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='no_rekening',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='picture1',
            field=models.ImageField(blank=True, max_length=455, null=True, upload_to=listings.models.upload_to),
        ),
        migrations.AlterField(
            model_name='listing',
            name='picture2',
            field=models.ImageField(blank=True, max_length=455, null=True, upload_to=listings.models.upload_to),
        ),
        migrations.AlterField(
            model_name='listing',
            name='picture3',
            field=models.ImageField(blank=True, max_length=455, null=True, upload_to=listings.models.upload_to),
        ),
        migrations.AlterField(
            model_name='listing',
            name='picture4',
            field=models.ImageField(blank=True, max_length=455, null=True, upload_to=listings.models.upload_to),
        ),
        migrations.AlterField(
            model_name='listing',
            name='picture5',
            field=models.ImageField(blank=True, max_length=455, null=True, upload_to=listings.models.upload_to),
        ),
    ]
