# Generated by Django 4.2.2 on 2023-07-26 10:32

from django.db import migrations, models
import django.db.models.deletion
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_no_rekening_alter_listing_picture1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='barang_dibeli',
            new_name='approve',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='fullName',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='phoneNumber',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buktiTransfer',
            field=models.ImageField(blank=True, max_length=455, null=True, upload_to=listings.models.upload_to),
        ),
        migrations.CreateModel(
            name='Kamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_day', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
                ('price_month', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
                ('price_year', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
                ('picture_room', models.ImageField(blank=True, max_length=455, null=True, upload_to=listings.models.upload_to)),
                ('room_size', models.CharField(blank=True, max_length=150, null=True)),
                ('address_room', models.CharField(blank=True, max_length=150, null=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kamar', to='listings.listing')),
            ],
        ),
    ]
