# Generated by Django 4.2.2 on 2023-07-26 13:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('listings', '0006_rename_barang_dibeli_transaction_approve_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rumah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('borough', models.CharField(blank=True, max_length=50, null=True)),
                ('no_rekening', models.CharField(blank=True, max_length=100, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('furnished', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('cctv', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('picture1', models.ImageField(blank=True, max_length=455, null=True, upload_to=listings.models.upload_to)),
                ('picture2', models.ImageField(blank=True, max_length=455, null=True, upload_to=listings.models.upload_to)),
                ('picture3', models.ImageField(blank=True, max_length=455, null=True, upload_to=listings.models.upload_to)),
                ('picture4', models.ImageField(blank=True, max_length=455, null=True, upload_to=listings.models.upload_to)),
                ('picture5', models.ImageField(blank=True, max_length=455, null=True, upload_to=listings.models.upload_to)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.owner')),
            ],
        ),
        migrations.RemoveField(
            model_name='kamar',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='review',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='listing',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
        migrations.AddField(
            model_name='kamar',
            name='rumah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kamar', to='listings.rumah'),
        ),
        migrations.AddField(
            model_name='review',
            name='rumah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='listings.rumah'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rumah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='listings.rumah'),
        ),
    ]
