# Generated by Django 4.2.2 on 2023-07-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_rumah_remove_kamar_listing_remove_review_listing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rumah',
            name='rooms',
        ),
    ]
