# Generated by Django 4.2.2 on 2023-07-27 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='rumah',
        ),
        migrations.AddField(
            model_name='rumah',
            name='price_per_year',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='kamar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='listings.kamar'),
        ),
    ]
