# Generated by Django 4.2.2 on 2023-07-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_remove_transaction_rumah_rumah_price_per_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='barang_dipesan',
        ),
        migrations.AddField(
            model_name='kamar',
            name='barang_dipesan',
            field=models.BooleanField(default=False),
        ),
    ]
