# Generated by Django 4.2.2 on 2023-07-31 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_transaction_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FasilitasKamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('kamar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fasilitaskamar', to='listings.kamar')),
            ],
        ),
        migrations.CreateModel(
            name='FasilitasRumah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('rumah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fasilitasrumah', to='listings.rumah')),
            ],
        ),
        migrations.DeleteModel(
            name='Fasilitas',
        ),
    ]
