# Generated by Django 4.2.2 on 2023-07-31 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_fasilitaskamar_fasilitasrumah_delete_fasilitas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fasilitasrumah',
            old_name='name',
            new_name='nama_fasilitas',
        ),
        migrations.RemoveField(
            model_name='fasilitasrumah',
            name='description',
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aturan', models.CharField(max_length=100)),
                ('rumah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='listings.rumah')),
            ],
        ),
    ]
