# Generated by Django 4.2.2 on 2023-07-31 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_rename_name_fasilitasrumah_nama_fasilitas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fasilitaskamar',
            name='description',
        ),
    ]
