# Generated by Django 4.2.2 on 2023-08-01 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_remove_fasilitaskamar_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rumah',
            old_name='price_per_year',
            new_name='price_per_month',
        ),
    ]
