# Generated by Django 4.2.2 on 2023-08-01 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_rename_price_per_year_rumah_price_per_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rumah',
            name='cctv',
        ),
        migrations.RemoveField(
            model_name='rumah',
            name='elevator',
        ),
        migrations.RemoveField(
            model_name='rumah',
            name='furnished',
        ),
        migrations.RemoveField(
            model_name='rumah',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='rumah',
            name='pool',
        ),
    ]
