# Generated by Django 4.2.2 on 2023-08-03 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_remove_rumah_cctv_remove_rumah_elevator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fasilitasrumah',
            old_name='nama_fasilitas',
            new_name='name',
        ),
    ]
