# Generated by Django 4.2.2 on 2023-08-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_rename_nama_fasilitas_fasilitasrumah_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasilitaskamar',
            name='name',
            field=models.CharField(choices=[('Wc', 'Wc'), ('Lemari', 'Lemari'), ('Meja Belajar', 'Meja Belajar'), ('Kursi', 'Kursi'), ('Tempat Tidur', 'Tempat Tidur'), ('Kasur', 'Kasur'), ('Ac', 'Ac')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fasilitasrumah',
            name='name',
            field=models.CharField(choices=[('Parkiran', 'Parkiran'), ('Kolam', 'Kolam'), ('Dapur Umum', 'Dapur Umum'), ('Wc Umum', 'Wc Umum'), ('Tangga', 'Tangga'), ('Lift', 'Lift'), ('CCTV', 'CCTV'), ('Lapangan', 'Lapangan'), ('Wifi', 'Wifi'), ('Tv Umum', 'Tv Umum'), ('Fasilitas Olahraga', 'Fasilitas Olahraga'), ('Security', 'Security'), ('Jasa Laundry', 'Jasa Laundry'), ('Kantin Umum', 'Kantin Umum'), ('Sarana Hiburan', 'Sarana Hiburan'), ('Rooftop', 'Rooftop'), ('Cleaning Service', 'Cleaning Service')], max_length=100),
        ),
    ]
