# Generated by Django 4.2.2 on 2023-08-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_alter_fasilitaskamar_name_alter_fasilitasrumah_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasilitasrumah',
            name='name',
            field=models.CharField(choices=[('Parkiran', 'Parkiran'), ('Kolam', 'Kolam'), ('Dapur Umum', 'Dapur Umum'), ('Wc Umum', 'Wc Umum'), ('Tangga', 'Tangga'), ('Lift', 'Lift'), ('CCTV', 'CCTV'), ('Lapangan', 'Lapangan'), ('Wifi', 'Wifi'), ('Tv Umum', 'Tv Umum'), ('Fasilitas Olahraga', 'Fasilitas Olahraga'), ('Security', 'Security'), ('Jasa Laundry', 'Jasa Laundry'), ('Kantin Umum', 'Kantin Umum'), ('Sarana Hiburan', 'Sarana Hiburan'), ('Cleaning Service', 'Cleaning Service')], max_length=100),
        ),
    ]
