# Generated by Django 4.2.2 on 2023-09-21 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_alter_fasilitasrumah_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleKamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aturan', models.CharField(max_length=100)),
                ('kamar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rulekamar', to='listings.kamar')),
            ],
        ),
        migrations.CreateModel(
            name='RuleRumah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aturan', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='rumah',
            name='price_per_month',
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
        migrations.AddField(
            model_name='rulerumah',
            name='rumah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rulerumah', to='listings.rumah'),
        ),
    ]
